### ISSUE TITLE
Unable to generate the Shrine that should have been generated

### ISSUE THREAD

**Issue by sosoyourinrin** [Some-Bunny/Planetside#11]
Originally, the first layer was supposed to generate a hidden room with an End of Everything Shrine inside. However, today when I opened the game and played it, I found that it was not generated. After restarting the game multiple times, I found that this room was not generated. I tried to disable unrelated mods to eliminate the problem, but in the end, only this mod and necessary pre mods were enabled, and this room was still not generated

**Comment by sosoyourinrin** [comment]
![屏幕截图 2024-07-25 002212](https://github.com/user-attachments/assets/3b23c9aa-c643-423e-8ada-3e9e3d6e9a05)

![20240725002442_1](https://github.com/user-attachments/assets/49752a71-5a98-40a7-a57e-1d1ebc6e979b)

**Comment by Some-Bunny** [comment]
if you have completed the unlock tied to that room, the chance of it generated it greatly reduced (5% instead of 100%), but due to jank this reduction is only applied every time you load the game after completing the unlock. 

Only thing to fix would be having the chance be reduced properly, but its janky to do.
